# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build the Android app for testing"
  lane :beta do
    gradle(task: "clean assembleRelease")
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy to Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
  end
end
